http_port: "8080"
redis_addr: "redis:6379"
worker_poll_interval: "5s"
cors_origins:
  - "https://stg.abakacademy.id"
access_token_ttl: "15m"
refresh_token_ttl: "168h"
otp_ttl: "5m"
google_client_id: ""
fazpass_base_url: "https://api.fazpass.com"
midtrans_env: "sandbox"
object_storage_endpoint: "storage.googleapis.com"
object_storage_public_endpoint: ""
object_storage_use_ssl: true
object_storage_region: "asia-southeast2"
object_storage_bucket_name: "abak_std"
object_storage_private_bucket_name: "abak_std"
