http_port: "8080"
redis_addr: "localhost:6379"
worker_poll_interval: "5s"
cors_origins:
  - "https://app.example.com"
access_token_ttl: "15m"
refresh_token_ttl: "168h"
otp_ttl: "5m"
google_client_id: ""
fazpass_base_url: "https://api.fazpass.com"
midtrans_env: "production"
smtp_host: ""
smtp_port: "587"
smtp_from: ""
smtp_from_name: ""
object_storage_endpoint: ""
object_storage_public_endpoint: ""
object_storage_use_ssl: true
object_storage_region: "asia-southeast2"
object_storage_bucket_name: "akademi-bimbel-prod"
object_storage_private_bucket_name: "akademi-bimbel-private-prod"
